version: '3'

services:
  # cpd-service
  cpd-service:
    build: ./CPD-service
    container_name: cpd-service

  stfx-core:
    build: ./core/stfXCore
    container_name: stfx-core
    ports:
      - 8080:8080
    environment:
      - PSR_endpoint=http://cpd-service:5000/cpd-all
    depends_on:
      - cpd-service